#pragma once

namespace onetoken {
enum ErrorCode {
  SUCCESS = 0,
  NOT_CONNECTED,
  CONNECT_FAILED,
  SERVER_CLOSED,
  NOT_AUTHORIZED,
  WRONG_PARAMETER,
  UNRECOGNIZED_REQ,
  WRONG_REQ_FORMAT,
  RESP_MESSAGE_FORMAT_ERROR,
  RESP_FAILED_MESSAGE,
  UNKNOWN_RESP_URI
};
}